export const Scopes = {
  STORE_PAYMENTS_ACCESS_TOKEN_CREATE: "store_payments_access_token_create",
  STORE_STOREFRONT_API: "store_storefront_api",
  STORE_STOREFRONT_API_CUSTOMER_IMPERSONATION:
    "store_storefront_api_customer_impersonation",
  STORE_APP_EXTENSIONS_MANAGE: "store_app_extensions_manage",
  STORE_CART: "store_cart",
  STORE_CART_READ_ONLY: "store_cart_read_only",
  STORE_CHANNEL_SETTINGS: "store_channel_settings",
  STORE_CHANNEL_SETTINGS_READ_ONLY: "store_channel_settings_read_only",
  STORE_CHANNEL_LISTINGS: "store_channel_listings",
  STORE_CHANNEL_LISTINGS_READ_ONLY: "store_channel_listings_read_only",
  STORE_CHECKOUT: "store_checkout",
  STORE_CHECKOUT_READ_ONLY: "store_checkout_read_only",
  STORE_CONTENT_CHECKOUT: "store_content_checkout",
  STORE_CONTENT_CHECKOUT_READ_ONLY: "store_content_checkout_read_only",
  STORE_V2_CONTENT: "store_v2_content",
  STORE_V2_CONTENT_READ_ONLY: "store_v2_content_read_only",
  STORE_V2_CUSTOMERS: "store_v2_customers",
  STORE_V2_CUSTOMERS_READ_ONLY: "store_v2_customers_read_only",
  STORE_V2_CUSTOMERS_LOGIN: "store_v2_customers_login",
  STORE_FULFILLMENT_METHODS_MANAGE: "store_fulfillment_methods_manage",
  STORE_FULFILLMENT_METHODS_READ_ONLY: "store_fulfillment_methods_read_only",
  STORE_V2_INFORMATION: "store_v2_information",
  STORE_V2_INFORMATION_READ_ONLY: "store_v2_information_read_only",
  STORE_V2_MARKETING: "store_v2_marketing",
  STORE_V2_MARKETING_READ_ONLY: "store_v2_marketing_read_only",
  STORE_METAFIELD_CHANGE_OWNER: "store_metafield_change_owner",
  STORE_METAFIELD_WRITE: "store_metafield_write",
  STORE_METAFIELD_WRITE_ALL: "store_metafield_write_all",
  STORE_V2_ORDERS: "store_v2_orders",
  STORE_V2_ORDERS_READ_ONLY: "store_v2_orders_read_only",
  STORE_ORDER_FULFILLMENT_MANAGE: "store_order_fulfillment_manage",
  STORE_ORDER_FULFILLMENT_READ_ONLY: "store_order_fulfillment_read_only",
  STORE_V2_TRANSACTIONS: "store_v2_transactions",
  STORE_V2_TRANSACTIONS_READ_ONLY: "store_v2_transactions_read_only",
  STORE_PAYMENTS_METHODS_READ: "store_payments_methods_read",
  STORE_V2_PRODUCTS: "store_v2_products",
  STORE_V2_PRODUCTS_READ_ONLY: "store_v2_products_read_only",
  STORE_SITES: "store_sites",
  STORE_SITES_READ_ONLY: "store_sites_read_only",
  STORE_INVENTORY: "store_inventory",
  STORE_INVENTORY_READ_ONLY: "store_inventory_read_only",
  STORE_LOCATIONS: "store_locations",
  STORE_LOCATIONS_READ_ONLY: "store_locations_read_only",
  STORE_STORED_PAYMENT_INSTRUMENTS_READ_ONLY:
    "store_stored_payment_instruments_read_only",
  STORE_STORED_PAYMENT_INSTRUMENTS: "store_stored_payment_instruments",
  STORE_THEMES_MANAGE: "store_themes_manage",
  STORE_THEMES_READ_ONLY: "store_themes_read_only",
};
